### ISSUE TITLE
Chebyshev expansion

### ISSUE THREAD

**Issue by PJthunder** [THUDM/ProNE#7]
I have checked your code for the NE enhancement. I guest the hype-parameter "step" actually means the number of items in the chebyshev expansion. Is it a hype-parameter which will influence the results significantly? Based on my experience, step =5 or 10 will not make big difference empirically right?

**Comment by lykeven** [comment]
Thanks for your attention to our work and kindly reviewing for our implementation!
You're right about the hyper-parameter 'step'. 

Due to the space limitation of the paper, we did not report experiments on parameter sensitivity but gave a default parameter settings. In fact, within a reasonable range of parameters, the performance of the algorithm is stable and will not change dramatically.

**Comment by PJthunder** [comment]
Cool. Thanks for your update!
