### ISSUE TITLE
Normalization

### ISSUE THREAD

**Issue by PJthunder** [THUDM/ProNE#8]
Have you applied any normalization or standardization steps for your model? I know some previous work has the normalization steps like LINE. Is that necessary for your model? Wondering whether that will influence the performance of downstream tasks.

**Comment by lykeven** [comment]
Actually, We apply L2 normalization steps in our model.
You can see  `U = preprocessing.normalize(U, "l2")` in line 44 and 57 of proNE.py.

Generally speaking, we should always normalize input feature(node embedding in our case), since the original input feature may vary a lot in several different dimensions. Otherwise, downstream model parameters may be dominated by one input dimension with a larger or smaller range. 
Normalized input feature usually performs better than the original one under downstream task like classification(Logistic regression on node classification in our case).
